POST http://localhost:8080/categoria
Content-Type: application/json
Accept: application/json


{
  "id": 1,
  "imagemSimboloUrl": "https://havaianas.com.br/dw/image213123213214534543543",
  "nome": "Tenis",
  "descricao": "Tenis Casuais"
}

###

GET http://localhost:8080/categoria/1
Accept: application/json

###

GET http://localhost:8080/categoria/1/produto?nome=Tenis&valorMinimo=50&valorMaximo=350
Accept: application/json
